// Writes api/_catalogue.js from scripts/properties.json — the list extracted
// from the region pages themselves.
//
// The spreadsheet pipeline (scripts/from-csv.mjs) writes the same file and is
// the one to use day to day. This exists because that pipeline refuses to
// generate while the CSV has errors outstanding, and the catalogue still has to
// match whatever is actually on the pages in the meantime.
//
// Replaces the old build-seed.mjs: same job, no SQL.
import { readFileSync, writeFileSync } from 'node:fs';

const rows = JSON.parse(readFileSync('scripts/properties.json', 'utf8'));
const js = v => JSON.stringify(v ?? null);

writeFileSync('api/_catalogue.js',
`// GENERATED by scripts/build-links.mjs. Do not hand-edit.
//
// Lives in api/ deliberately: files here are function source, not static
// output, so this is not fetchable from the site. ${rows.length} properties.

export const PROPERTIES = {
${rows.map(r => `  ${js(r.slug)}: { url: ${js(r.owner_url)}, title: ${js(r.title)}, region: ${js(r.region)} },`).join('\n')}
};

export const lookup = slug =>
  Object.prototype.hasOwnProperty.call(PROPERTIES, slug) ? PROPERTIES[slug] : null;

export const SLUGS = Object.keys(PROPERTIES);
`);

console.log(`api/_catalogue.js — ${rows.length} properties`);
