import { readFileSync, writeFileSync } from 'node:fs';
const rows = JSON.parse(readFileSync('scripts/properties.json', 'utf8'));
const q = s => s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`;
const values = rows.map(r =>
  `  (${q(r.slug)}, ${q(r.region)}, ${q(r.owner_url)}, ${q(r.title)}, ${q(r.sub)})`
).join(',\n');
writeFileSync('db/002_seed_properties.sql',
`-- Generated by scripts/build-seed.mjs from the region pages. Do not hand-edit:
-- re-run the extractor instead. ${rows.length} properties.

insert into properties (slug, region, owner_url, title, sub) values
${values}
on conflict (slug) do update
  set region = excluded.region,
      owner_url = excluded.owner_url,
      title = excluded.title,
      sub = excluded.sub;
`);
console.error(`db/002_seed_properties.sql — ${rows.length} rows`);
